LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE 	:= readini
LOCAL_CFLAGS 	:= -fPIC
LOCAL_SRC_FILES	:= ReadINI.c 

LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
include $(BUILD_STATIC_LIBRARY)
